### ISSUE TITLE
How to use plu-ts v0.5.5 or v0.6.0

### ISSUE THREAD

**Issue by arvrastart** [michele-nuzzi/hello-pluts-react-final#1]
I run npm update @harmoniclabs/plu-ts , update plu-ts to v0.5.5 or v0.6.0,  then run " npm run dev " will error,  how to solve it？ thank you.

**Comment by michele-nuzzi** [comment]
Hey @arvrastart, thanks for the issue; the main branch was created using version ^0.3.0

Will fork it and update the main to work with 0.5.*;

P.S. avoid 0.6.* until released (there should not be any `-dev*` or similar postfix in the version)

**Comment by arvrastart** [comment]
> Hey @arvrastart, thanks for the issue; the main branch was created using version ^0.3.0
> 
> Will fork it and update the main to work with 0.5.*;
> 
> P.S. avoid 0.6.* until released (there should not be any `-dev*` or similar postfix in the version)

Cool, thank you for your efforts, great and meaningful work.
